modLoader="javafml" 
loaderVersion="[49,)" 
license="GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Infinity Craft"
description="${mod_description}"
authors="${mod_authors}"

[[dependencies.infcraft]]
    modId="forge"
    mandatory=true
    versionRange="[49.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.infcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="1.21.1"
    ordering="NONE"
    side="BOTH"